[[redirects]]
  from = "/api/geocode"
  to = "/.netlify/functions/geocode"
  status = 200
  force = true

[[redirects]]
  from = "/api/geocode-latest"
  to = "/.netlify/functions/geocode-latest"
  status = 200
  force = true
